version: '3.9'
name: 'bookstore-microservices'
services:
  catalog-service:
    image: amithkashyaprv/bookstore-catalog-service
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://catalog-db:3306/catalog-db
      - DB_USERNAME=catalog
      - DB_PASSWORD=catalog
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      catalog-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  order-service:
    image: amithkashyaprv/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://orders-db:3306/orders-db
      - DB_USERNAME=orders
      - DB_PASSWORD=orders
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      orders-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m

  notification-service:
    image: amithkashyaprv/bookstore-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:mysql://notifications-db:3306/notifications-db
      - DB_USERNAME=notifications
      - DB_PASSWORD=notifications
      - RABBITMQ_HOST=bookstore-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      notifications-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m