version: '3.9'
name: 'bookstore-microservices'
services:
  catalog-db:
    image: mysql:8.4
    container_name: catalog-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catalog-db
      - MYSQL_USER=catalog
      - MYSQL_PASSWORD=catalog
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p password | grep 'mysqld is alive'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  orders-db:
    image: mysql:8.4
    container_name: orders-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=orders-db
      - MYSQL_USER=orders
      - MYSQL_PASSWORD=orders
    ports:
      - "23306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p password | grep 'mysqld is alive'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: bookstore-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m

  notifications-db:
    image: mysql:8.4
    container_name: notifications-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=notifications-db
      - MYSQL_USER=notifications
      - MYSQL_PASSWORD=notifications
    ports:
      - "33306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p password | grep 'mysqld is alive'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"