version: '3.9'
name: 'bookstore-microservices'
services:
  catalog-db:
    image: mysql:8.4
    container_name: catalog-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catalog-db
      - MYSQL_USER=catalog
      - MYSQL_PASSWORD=catalog
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p password | grep 'mysqld is alive'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m